require("wise1685.plugins-setup")
require("wise1685.core.options")
require("wise1685.core.keymaps")
require("wise1685.core.colorscheme")
require("wise1685.plugins.comment")
require("wise1685.plugins.nvim-tree")
require("wise1685.plugins.lualine")
require("wise1685.plugins.telescope")
require("wise1685.plugins.nvim-cmp")
require("wise1685.plugins.lsp.mason")
require("wise1685.plugins.lsp.lspsaga")
require("wise1685.plugins.lsp.lspconfig")
require("wise1685.plugins.lsp.null-ls")
require("wise1685.plugins.autopairs")
require("wise1685.plugins.treesitter")
require("wise1685.plugins.gitsigns")
require("wise1685.plugins.bufferline")
vim.cmd([[hi Normal guibg=NONE ctermbg=NONE]])
